# Generated by Django 2.1 on 2018-08-01 18:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogfront', '0003_auto_20180801_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
