# Generated by Django 2.1 on 2018-08-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogfront', '0005_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
    ]
